; EMAIL_USERNAME = "ark550898@gmail.com"
; EMAIL_PASSWORD = "zydvwxeqpkblnlsc"
; GOOGLE_CLIENT_ID = "645634369656-1h6lnufdp2qk1tlk1tljbn5sp3n7g47g.apps.googleusercontent.com"
; GOOGLE_CLIENT_SECRET = "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"

; backend/config.ini

[Google OAuth]
GOOGLE_CLIENT_ID = "645634369656-1h6lnufdp2qk1tlk1tljbn5sp3n7g47g.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

[Email Config]
EMAIL_USERNAME = "ark550898@gmail.com"
EMAIL_PASSWORD = "zydvwxeqpkblnlsc"